import type { NextPage } from 'next'
import Head from 'next/head'
import { getAllPosts } from '../lib/apit'
import { Post } from '../types/post'

type Props = {
  allPosts: Post[]
}

const Home: NextPage<Props> = ({allPosts}) => {
  return (
    <div>
      <Head>
        <title>Mochi Tale</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Mochi Tale
          {
            allPosts.map(post => 
              <pre key={post.slug}>
                {post.author.name}
                {post.slug}
                {post.title}
              </pre>
            )
          }
        </h1>
      </main>

      <footer >
      </footer>
    </div>
  )
}

export default Home

export const getStaticProps = async () => {
  const allPosts = getAllPosts([
    'title',
    'date',
    'slug',
    'author',
    'coverImage',
    'excerpt',
  ])

  return {
    props: { allPosts },
  }
}